/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lifeunderwaterapp;

/**
 *
 * @author CamaraAdmin
 */
public class LifeUnderWaterGUI extends javax.swing.JFrame {

    
     /* creates LifeUnderWaterGUI*/
    public LifeUnderWaterGUI() {
        initComponents();
        backBtn.setVisible(true);
        floraBtn.setVisible(true);
        pollBtn.setVisible(true);
        wildBtn.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        floraBtn = new javax.swing.JButton();
        wildBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        pollBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        floraBtn.setText("Flora");
        floraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floraBtnActionPerformed(evt);
            }
        });

        wildBtn.setText("Wildlife");
        wildBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wildBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");

        pollBtn.setText("Pollution");
        pollBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pollBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(floraBtn)
                .addGap(243, 243, 243)
                .addComponent(pollBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                .addComponent(wildBtn)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(backBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(floraBtn)
                    .addComponent(wildBtn)
                    .addComponent(pollBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 414, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void floraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floraBtnActionPerformed

        //The action tht is performed when butto is clicked
        FloraGUI floraGUI = new FloraGUI();
        floraGUI.setVisible(true);
        
    }//GEN-LAST:event_floraBtnActionPerformed

    private void wildBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wildBtnActionPerformed
        // TODO add your handling code here:
        WildlifeGUI wildlifeGUI = new WildlifeGUI();
        wildlifeGUI.setVisible(true);
    }//GEN-LAST:event_wildBtnActionPerformed

    private void pollBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pollBtnActionPerformed
        // TODO add your handling code here:
        PollutionGUI pollutionGUI = new PollutionGUI();
        pollutionGUI.setVisible(true);
    }//GEN-LAST:event_pollBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
  /* Create and display the form, can also do the styling of the window here */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //the most important bit of code for GUI's below;
                new LifeUnderWaterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton floraBtn;
    private javax.swing.JButton pollBtn;
    private javax.swing.JButton wildBtn;
    // End of variables declaration//GEN-END:variables
}
